# Generated by Django 2.2.10 on 2020-03-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('bossid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('bossname', models.CharField(max_length=255, verbose_name='老板')),
                ('intro', models.CharField(default='', max_length=255, null=True, verbose_name='介绍')),
            ],
            options={
                'verbose_name': 'boss表',
                'db_table': 'tb_boss',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=255, verbose_name='名字')),
                ('member', models.IntegerField(default=1, verbose_name='成员数量')),
                ('hot', models.IntegerField(default=0, null=True, verbose_name='热度')),
                ('intro', models.CharField(default='', max_length=511, null=True, verbose_name='介绍')),
                ('market', models.CharField(default='', max_length=256, null=True, verbose_name='经营情况')),
                ('mainphoto', models.CharField(default='', max_length=255, null=True, verbose_name='图片')),
            ],
            options={
                'verbose_name': '公司',
                'db_table': 'tb_company',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('distid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=255, verbose_name='名字')),
                ('ishot', models.BooleanField(default=False, null=True, verbose_name='是否热门城市')),
                ('intro', models.CharField(default='', max_length=255, null=True, verbose_name='介绍')),
                ('parent', models.ForeignKey(db_column='pid', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.District', verbose_name='父级行政区')),
            ],
            options={
                'verbose_name': '地区表',
                'verbose_name_plural': '地区表',
                'db_table': 'tb_district',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('privid', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('method', models.CharField(default='', max_length=15, null=True, verbose_name='方式')),
                ('url', models.CharField(default='', max_length=1024, null=True, verbose_name='对应url')),
                ('detail', models.CharField(default='', max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限管理',
                'db_table': 'tb_privilege',
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('recruitid', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('number', models.IntegerField(default=1, verbose_name='招聘数量')),
                ('min_salary', models.IntegerField(default=0, null=True, verbose_name='最低薪水')),
                ('max_salary', models.IntegerField(default=0, null=True, verbose_name='最高薪水')),
                ('detail', models.CharField(default='', max_length=511, null=True, verbose_name='职位详情')),
                ('pubdate', models.DateField(auto_now_add=True, null=True, verbose_name='发布日期')),
                ('street', models.CharField(default='', max_length=255, null=True, verbose_name='办公地址')),
                ('hassubway', models.IntegerField(default=False, null=True, verbose_name='交通情况')),
                ('boss', models.ForeignKey(db_column='bossid', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Boss', verbose_name='老板')),
                ('company', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.Company', verbose_name='公司')),
                ('distinct_level2', models.ForeignKey(db_column='distid2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.District', verbose_name='二级行政区')),
                ('distinct_level3', models.ForeignKey(db_column='distid3', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.District', verbose_name='三级行政区')),
            ],
            options={
                'verbose_name': '职位信息',
                'db_table': 'tb_recruit',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('recruiterid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=255, verbose_name='名字')),
                ('tel', models.CharField(max_length=20, verbose_name='联系方式')),
                ('servstar', models.IntegerField(default=0, verbose_name='评价')),
                ('intro', models.CharField(default='', max_length=255, null=True, verbose_name='介绍')),
                ('company', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.Company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '招聘人表',
                'db_table': 'tb_recruiter',
            },
        ),
        migrations.CreateModel(
            name='RecruitType',
            fields=[
                ('typeid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(default='', max_length=255, null=True, verbose_name='类型')),
            ],
            options={
                'verbose_name': '职位类型',
                'db_table': 'tb_recruit_type',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False, verbose_name='角色id')),
                ('rolename', models.CharField(max_length=255, null=True, verbose_name='角色名')),
            ],
            options={
                'verbose_name': '角色',
                'db_table': 'tb_role',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagid', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('content', models.CharField(default='', max_length=20, null=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '职位标签',
                'db_table': 'tb_tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('realname', models.CharField(default='', max_length=20, null=True, verbose_name='真实姓名')),
                ('sex', models.BooleanField(default=True, null=True, verbose_name='性别')),
                ('birth', models.DateTimeField(auto_now_add=True, null=True, verbose_name='生日')),
                ('intro', models.CharField(default='', max_length=256, verbose_name='用户介绍')),
                ('tel', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('email', models.CharField(default='', max_length=255, unique=True, verbose_name='邮箱')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('point', models.IntegerField(default=0, verbose_name='积分')),
                ('ismember', models.BooleanField(default=False, verbose_name='是否会员')),
                ('lastvisit', models.DateTimeField(auto_now_add=True, verbose_name='最近登录')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='RolePrivilege',
            fields=[
                ('role_priv_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('priv', models.ForeignKey(db_column='privid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Privilege', verbose_name='权限')),
                ('role', models.ForeignKey(db_column='roleid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限',
                'db_table': 'tb_role_privilege',
                'unique_together': {('role', 'priv')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='privs',
            field=models.ManyToManyField(default=0, through='web.RolePrivilege', to='web.Privilege', verbose_name='对应权限'),
        ),
        migrations.CreateModel(
            name='RecruiterRecruit',
            fields=[
                ('recruiter_recruit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('recruit', models.ForeignKey(db_column='recruitid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Recruit', verbose_name='职位')),
                ('recruiter', models.ForeignKey(db_column='recruiterid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Recruiter', verbose_name='招聘人')),
            ],
            options={
                'verbose_name': '招聘人负责职位',
                'db_table': 'tb_recruiter_recruit',
                'unique_together': {('recruiter', 'recruit')},
            },
        ),
        migrations.AddField(
            model_name='recruiter',
            name='recruit',
            field=models.ForeignKey(db_column='recruitid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.RecruiterRecruit', verbose_name='负责职位'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='recruiter',
            field=models.ForeignKey(db_column='recruiterid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.RecruiterRecruit', verbose_name='招聘人'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='type',
            field=models.ForeignKey(db_column='typeid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.RecruitType', verbose_name='职位类型'),
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('logid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('ipaddr', models.CharField(max_length=255, verbose_name='ip地址')),
                ('logdate', models.DateTimeField(auto_now_add=True, verbose_name='登录日期')),
                ('devcode', models.CharField(default='', max_length=255, verbose_name='设备编码')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'db_table': 'tb_login_log',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('photoid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('path', models.CharField(default='', max_length=255, null=True, verbose_name='图片')),
                ('company', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.Company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '公司图片',
                'db_table': 'tb_company_photo',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='distinct',
            field=models.ForeignKey(db_column='distid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.District', verbose_name='行政区'),
        ),
        migrations.AddField(
            model_name='boss',
            name='company',
            field=models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.Company', verbose_name='公司'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('role', models.ForeignKey(db_column='roleid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Role', verbose_name='角色id')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户角色',
                'db_table': 'tb_user_role',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RecruitTag',
            fields=[
                ('recruit_tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('recruit', models.ForeignKey(db_column='recruitid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Recruit', verbose_name='职位')),
                ('tag', models.ForeignKey(db_column='tagid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '职位对应的标签',
                'db_table': 'tb_recruit_tag',
                'unique_together': {('recruit', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='RecruiterCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('company', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.Company', verbose_name='公司')),
                ('recruiter', models.ForeignKey(db_column='recruiterid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.Recruiter', verbose_name='招聘人')),
            ],
            options={
                'verbose_name': '招聘人公司表',
                'db_table': 'tb_recruiter_company',
                'unique_together': {('recruiter', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('recorddate', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('recruit', models.ForeignKey(db_column='recruitid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.Recruit', verbose_name='职位')),
                ('user', models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览记录',
                'db_table': 'tb_record',
                'unique_together': {('user', 'recruit')},
            },
        ),
        migrations.CreateModel(
            name='BossCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('boss', models.ForeignKey(db_column='bossid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.Boss', verbose_name='boss')),
                ('company', models.ForeignKey(db_column='compayid', on_delete=django.db.models.deletion.DO_NOTHING, to='web.Company', verbose_name='公司')),
            ],
            options={
                'verbose_name': 'boss-公司表',
                'db_table': 'tb_boss_company',
                'unique_together': {('boss', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('applyid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='浏览序号')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加收藏时间')),
                ('recruit', models.ForeignKey(db_column='recruitid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Recruit', verbose_name='职位')),
                ('user', models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'db_table': 'tb_apply',
                'unique_together': {('user', 'recruit')},
            },
        ),
    ]
